### PR TITLE
 Add setName and setSymbols governance methods

### PR DESCRIPTION
**Pull request by chriswessels**
- Updated default symbol to `concat("yv", DetailedERC20(_token).symbol())`
- Updated default name to `self.name = concat(DetailedERC20(_token).symbol(), " yVault")`
- Adds setName and setSymbol methods for governance
- Updated Vault deployment tests
- Added new tests for setName and setSymbol

### CODE REVIEW

**Comment by banteg** [comment]
The change looks good, but can we keep the defaults?

**Comment by chriswessels** [comment]
Thanks @banteg.

The defaults implemented in this PR reflect the latest outcomes in this naming conventions doc, but discussion is still ongoing so I have marked this PR as `WIP`: https://docs.google.com/spreadsheets/d/1oKnvHxeQRDLAtiBWFpdmDIbJVEGeZdQ0l4vE5OvVoV0/edit#gid=467442383

**Comment by milkyklim** [comment]
@banteg do you want to remove setters? What do you mean but keep the defaults?

**Comment by banteg** [comment]
I wasn't aware of the doc, disregard my comment.

**Review by banteg — APPROVED** [review]
Looks good to me. Bump version to `0.1.2`.

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
